version: 0.2
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t react-app:latest .
  post_build:
    commands:
      - docker tag react-app:latest ${DOCKERHUB_USER}/react-app:latest
      - docker push ${DOCKERHUB_USER}/react-app:latest